name: Nakamoto
favicon: null
layout_spectrum: 0.25717
typography_spectrum: 0.24207601533271372
title: Nakamoto Virtual Presence
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff6033'
    - '#ffa033'
    - '#ff8e33'
    - '#ff3e33'
    - '#ffcb33'
  brandStrength: 0.4566868126858026
  lightness: 0.875
  saturation: 0.762338045053184
  rhythmicContrast: 0.25
purpose: []
